sudo: required
language: generic
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project hello-k8s-329805
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials hello-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t mkulaa1/react-app-test -f ./react-app/Dockerfile.dev ./react-app

script:
  - docker run -e CI=true mkulaa1/react-app-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master